language: ruby
sudo: true
rvm:
  - 2.2.1
cache:
  - bundler
  - npm
before_install:
  - nvm install 0.12
  - nvm use 0.12
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
install:
  - bundle install
  - npm install
  - npm install -g http-server
  - bundle exec jekyll build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start