language: ruby
rvm:
- 2.2.1
cache:
- bundler
notifications:
  slack:
    secure: PQj27G9cVCth3ErgBdJoNCd2+slMdF+G/nrVqDKuMsTx9X8wU24LKIdxSqKC7IXQh6rG9Zfbsg/2LNMA+0reIr0ErUN/UiqUn+cXdIo8ScLui409c/K6oEY/lKW6WQFpGJWJUUvk4UddYWiB+nAGx5BSkR8ca9XKf46N9SPGQ41m4FuB8GYMm7U79XZHW4Cf2QFb8as6593IOIPytcaly+X88iDW+Pq895kSrm3J2abPGIU3NMgIyvTHcf1l6JfwTwXZ+mI3n/jELb88TcS3aV25h18Y4C9S1RGtUiyF9qOFTvDlaFIhXuxAygYOHJpFaqE2VO9SkDi8zn4vi1Cth+/EdO76Ehw1XVtjyhsONWMi0/25SgwfLqkvWTWBPDQUD4XUSj20NPwsC8zOBqCQdMLn0BIcounk7501Z4rAIjeOVcOaWiFxZyaC7dbLIEt1Q4+kuZ4LW0isFta6MqN+L9MZc4fRAe9rEo6Hb/iFx11AhzI1MNAsIqZ2fnjrIpyHbgJ3jW4Uh6GE8tXxUnfYuf5LpjbAibICAQhErIYIYwTysk3GHBYj+vzBwBh1UazexFZBpyATXIofWRvvq+8J+EaN5gl47Qn9D2Dfu9zbvPMU2u7Vk4JE1uoZzpi0XvU5hJ8wBh5bMBJIhV1SWAC2POXdrod2DZCI+ytDF16zPh0=
