language: node_js
node_js:
- node

cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
  - vendor/bundle
  - $HOME/.rvm/user/installs

before_install:
- if [[ ! -d $HOME/.rvm/user/installs ]]; then rvm install ruby-2.3.1; fi
- rvm use 2.3.1
- bundle install --deployment

before_script:
- export PATH="$(yarn bin):$PATH"

script:
- gulp lint
- gulp compile --env production
- bundle exec htmlproofer ./_site --check-favicon --check-html --check-external-hash --check-html --check-img-http --check-opengraph

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GH_TOKEN
  repo: molovo/molovo.github.io
  target_branch: master
  on:
    branch: master

notifications:
  email: false

env:
  global:
  - secure: uR8p7P03HqPM26nPLCNyq6xE5eGANPNAeGqP8HExeG8zr6mp2Jcq1ZOObkwHdYZyZ0Mg+V3IliF0zREV/+l6/1SaK9Vg7Z7Sx4pQvolE94taCRl2IarqhnmFfT9a0ng33Xo5Q8zqpBIM9K9MoMLhYmHRfvUT2ntQI1UqGt9/u833wR8TRHaGJNhuqlWfLk+QdWUDqftD0KwLKX2lla5iv/S8PkrOwUS2ELhZJqA86MHRE6Gv4fmzJHWrEiDyFHyra75DDgor7w6EZFxF9qsLQK1M5jM1zhSWARf26dInTe6y8ilQ/ViBXngrowm+ZPWldqEOXTau6+nvJR/RMugWifwO/pAagYTgENK9FfexcHnjeh8yDn/RKTYIVF/ZZnvAInSBETjlWNnHL/4zv7HGL3ASA/6xQ1ZkhU9po9lgYWOZSt9qztGG0bDAlBNDj7cDPJdgDUjgRivCAhH6Cv2kBmC7zePop0JgiWJJxKCYAtS/WjwLMy2a+ZldVr57a8+QIY+pcQYlXncbbQOrl9Loa4WqiCU7PH/BM1Ga4hefFLOFnYv/2NBEM4Tl1NbIT25yVjQHPU2/j8CMGfin/lhiPytKngN7uqtcSxK/yPodjmUl+yrbQh1csoRT0hHUHNPFxHhV5FX/YmzodaNMi+stfqV3k+nEbPZZTqeWxt1wJbo=
