# Site settings
title: molovo
name: molovo
logo: /img/amp-logo.png
email: hi@molovo.co
description: >
  James Dinsdale is a web .
baseurl: ''
url: 'https://molovo.co'
twitter_username: molovo
github_username:  molovo
medium_username: molovo
dribbble_username: molovo
instagram_username: jameswdinsdale
author: James Dinsdale
environment: production

# Build settings
permalink: /writing/:title/
pagination:
  enabled: true
  per_page: 5
  permalink: /:num/
  sort_reverse: true
keep_files:
  - css
  - js
  - img
include:
  - _headers
  - _redirects
exclude:
  - _assets
  - coffeelint.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - netlify.toml
  - node_modules
  - package.json
  - validate.rb
  - yarn.lock

collections:
  studies:
    output: false
    permalink: /studies/:name/
defaults:
- scope:
    path: /writing/
    type: posts
  values:
    layout: post
    pagination: true
- scope:
    path: /studies/
    type: studies
  values:
    layout: study
    pagination: false

autopages:
  enabled: true
  collections:
    enabled: false
  categories:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: 'Posts tagged with &lsquo;:tag&rsquo;'
    permalink: '/tag/:tag/'

# Markdown Configuration
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - strikethrough
    - with_toc_data
    - smart

# Include a couple plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-webmention_io
  - jekyll-typogrify
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 50
  sizes:
    - width: 320
    - width: 480
    - width: 640
    - width: 800
    - width: 1024
    - width: 1280
    - width: 1440
    - width: 1680
    - width: 1920
  auto_rotate: true
  base_path: ''
  cache: true
  output_path_format: '%{dirname}/resized/%{filename}-%{width}x%{height}.%{extension}'
  save_to_source: true
  strip: true

# Webmentions
webmentions:
  username: molovo.co
  # skip bad URLs for 5 days
  cache_bad_uris_for: 5
  # I moved to www and then to https, so…
  legacy_domains:
    - http://molovo.co.uk
    - http://www.molovo.co.uk
    - https://molovo.co.uk
    - https://www.molovo.co.uk
    - http://molovo.co
    - http://www.molovo.co
    - https://www.molovo.co
  js: false
  templates:
    count: _includes/webmentions/count.html
