# Site settings
title: molovo - Web Design and Development
name: molovo
logo: /img/amp-logo.png
email: hi@molovo.co
description: >
  molovo.co is the home of Southsea web designer and developer James Dinsdale.
baseurl: ''
url: 'https://molovo.co'
twitter_username: molovo
github_username:  molovo
medium_username: molovo
dribbble_username: molovo
instagram_username: jameswdinsdale
author: James Dinsdale
environment: production

# Include a couple plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-webmention_io

# Build settings
permalink: /writing/:title/
pagination:
  enabled: true
  per_page: 5
  permalink: /:num/
  sort_reverse: true
keep_files:
  - css
  - js
  - img
include:
  - _headers
  - _redirects
exclude:
  - _assets
  - coffeelint.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.coffee
  - netlify.toml
  - node_modules
  - package.json
  - yarn.lock

collections:
  # Create pages for archived posts without including them in the listing
  archive:
    output: true
    permalink: /writing/:name/
  studies:
    output: false
    permalink: /studies/:name/
defaults:
- scope:
    path: ""
    type: archive
  values:
    layout: post
    pagination: false
- scope:
    path: /writing/
    type: posts
  values:
    layout: post
    pagination: true
- scope:
    path: /studies/
    type: studies
  values:
    layout: study
    pagination: false

# Markdown Configuration
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - strikethrough
    - with_toc_data
    - smart

# Include a couple plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-webmention_io

# Jekyll Picture Tag settings
picture:
  source: "_assets/img"
  output: "img"
  markup: "picture"
  presets:
    default:
      ppi: [1, 2]
      source_large:
        media: "(min-width: 64em)"
        width: "1280"
      source_medium:
        media: "(min-width: 40em)"
        width: "960"
      source_default:
        width: "600"

# Webmentions
webmentions:
  username: molovo.co
  # skip bad URLs for 5 days
  cache_bad_uris_for: 5
  # I moved to www and then to https, so…
  legacy_domains:
    - http://molovo.co.uk
    - http://www.molovo.co.uk
    - https://molovo.co.uk
    - https://www.molovo.co.uk
    - http://molovo.co
    - http://www.molovo.co
    - https://www.molovo.co
  js: false
