name: Molovo
url: 'https://molovo.co'
markdown: rdiscount
rdiscount:
  extensions: [smart, footnotes]
higlighter: pygments
permalink: /:categories/:title
exclude: ['.gitignore', 'molovo.sublime-project', 'molovo.sublime-workspace', '/.sass_cache', '/node_modules', '/gulpfile.js', '/src', '/package.json', '.git', '.gitignore', 'temp', '/report', '/reports', 'Gemfile.lock', 'Gemfile', 'Rakefile']
include: ['.htaccess']
encoding: utf-8
destination: '_site'
description: 'Hi. I&rsquo;m James, and I design things for the web, like websites, apps, blogs, icons and logos.'