name: Molovo
url: 'https://molovo.co'
markdown: rdiscount
rdiscount:
  extensions: [smart, footnotes]
higlighter: pygments
permalink: /:categories/:title
exclude: ['.gitignore', 'molovo.sublime-project', 'molovo.sublime-workspace', '/assets/.sass_cache', '/assets/node_modules', '/assets/gulpfile.js', '/assets/src', '/assets/package.json', '.git', '.gitignore', 'temp', '/assets/report', '/assets/reports']
include: ['.htaccess']
encoding: utf-8
destination: 'public_html'
description: 'Hi. I&rsquo;m James, and I design things for the web, like websites, apps, blogs, icons and logos.'