# Global settings applied to the whole site.
[build]
  publish = "_site"
  command = "gulp compile --env production"

[context.branch-deploy]
  command = "gulp compile"

[context.staging]
  command = "gulp compile --env staging"